# Generated by Django 4.2.3 on 2023-08-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='url',
            field=models.URLField(blank=True, help_text='<i>Введите URL сайта</i>', verbose_name='Ссылка'),
        ),
    ]
