# Generated by Django 4.2.3 on 2023-08-22 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_shoppingcart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'verbose_name': 'Корзина пользователя', 'verbose_name_plural': 'Список пользовательских корзин'},
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='user_address',
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='contact',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cart_contact', to='shop.contact', verbose_name='Контакт'),
            preserve_default=False,
        ),
    ]
