# Generated by Django 4.2.3 on 2023-08-23 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_basket_quantity_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='contact',
        ),
        migrations.AddField(
            model_name='basket',
            name='final_price',
            field=models.FloatField(default=0, verbose_name='Цена в корзине'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='product',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_product', to='shop.productinfo', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
    ]
