# Generated by Django 4.2.3 on 2023-08-24 11:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0008_remove_basket_contact_basket_final_price_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Basket',
            new_name='BasketItem',
        ),
    ]
