# Generated by Django 4.2.3 on 2023-08-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_rename_basket_basketitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketitem',
            name='final_price',
        ),
        migrations.AddField(
            model_name='basketitem',
            name='price',
            field=models.FloatField(default=0, verbose_name='Цена за отдельный товар'),
        ),
    ]
