# Generated by Django 4.2.3 on 2023-08-24 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0010_remove_basketitem_final_price_basketitem_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basketitem',
            options={'verbose_name': 'Товар в пользовательской корзине', 'verbose_name_plural': 'Товары в пользовательской корзине'},
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_price', models.FloatField(default=0, verbose_name='Цена в корзине')),
                ('basket_items', models.ManyToManyField(blank=True, related_name='basket_items', to='shop.basketitem', verbose_name='Товары')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='basket_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Корзина пользователя',
                'verbose_name_plural': 'Список пользовательских корзин',
            },
        ),
    ]
