# Generated by Django 4.2.3 on 2023-08-27 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_basketitem_options_basket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='basket_items',
        ),
        migrations.RemoveField(
            model_name='basketitem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='basketitem',
            name='user',
        ),
        migrations.AddField(
            model_name='basket',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='basket_items', through='shop.BasketItem', to='shop.productinfo', verbose_name='Товары'),
        ),
        migrations.AddField(
            model_name='basketitem',
            name='basket',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cart_product', to='shop.basket', verbose_name='Продукт'),
            preserve_default=False,
        ),
    ]
